#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Demo_EMS")]
public partial class DataClasses2DataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertTable_1(Table_1 instance);
  partial void UpdateTable_1(Table_1 instance);
  partial void DeleteTable_1(Table_1 instance);
  #endregion
	
	public DataClasses2DataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Demo_EMSConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Table_1> Table_1s
	{
		get
		{
			return this.GetTable<Table_1>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_1")]
public partial class Table_1 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ProjectId;
	
	private string _ProjectName;
	
	private string _ProjectGroupEmail;
	
	private string _LastAction;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProjectIdChanging(int value);
    partial void OnProjectIdChanged();
    partial void OnProjectNameChanging(string value);
    partial void OnProjectNameChanged();
    partial void OnProjectGroupEmailChanging(string value);
    partial void OnProjectGroupEmailChanged();
    partial void OnLastActionChanging(string value);
    partial void OnLastActionChanged();
    #endregion
	
	public Table_1()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ProjectId
	{
		get
		{
			return this._ProjectId;
		}
		set
		{
			if ((this._ProjectId != value))
			{
				this.OnProjectIdChanging(value);
				this.SendPropertyChanging();
				this._ProjectId = value;
				this.SendPropertyChanged("ProjectId");
				this.OnProjectIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectName", DbType="VarChar(400)")]
	public string ProjectName
	{
		get
		{
			return this._ProjectName;
		}
		set
		{
			if ((this._ProjectName != value))
			{
				this.OnProjectNameChanging(value);
				this.SendPropertyChanging();
				this._ProjectName = value;
				this.SendPropertyChanged("ProjectName");
				this.OnProjectNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectGroupEmail", DbType="NVarChar(250)")]
	public string ProjectGroupEmail
	{
		get
		{
			return this._ProjectGroupEmail;
		}
		set
		{
			if ((this._ProjectGroupEmail != value))
			{
				this.OnProjectGroupEmailChanging(value);
				this.SendPropertyChanging();
				this._ProjectGroupEmail = value;
				this.SendPropertyChanged("ProjectGroupEmail");
				this.OnProjectGroupEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastAction", DbType="VarChar(2)")]
	public string LastAction
	{
		get
		{
			return this._LastAction;
		}
		set
		{
			if ((this._LastAction != value))
			{
				this.OnLastActionChanging(value);
				this.SendPropertyChanging();
				this._LastAction = value;
				this.SendPropertyChanged("LastAction");
				this.OnLastActionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
