//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeastCustomAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeastCustomAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02.08.08.02.
        /// </summary>
        internal static string EXCEL_BONDECN_CURRENTVERSION {
            get {
                return ResourceManager.GetString("EXCEL_BONDECN_CURRENTVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 058C858C-A3FE-40E0-8145-C8413111ECC3.
        /// </summary>
        internal static string EXCEL_BONDECN_OBJGUID {
            get {
                return ResourceManager.GetString("EXCEL_BONDECN_OBJGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02.08.08.02.
        /// </summary>
        internal static string EXCEL_CUSTOMBOOKS_CURRENTVERSION {
            get {
                return ResourceManager.GetString("EXCEL_CUSTOMBOOKS_CURRENTVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8483b7b4-f8a3-4a23-8ef4-828fe3f0fd8f.
        /// </summary>
        internal static string EXCEL_CUSTOMBOOKS_OBJGUID {
            get {
                return ResourceManager.GetString("EXCEL_CUSTOMBOOKS_OBJGUID", resourceCulture);
            }
        }
    }
}
