#region Includes
	using System;
	using System.Data;
	using System.Text;
#endregion

namespace VCM.EMS.Biz
{

[Serializable]
public class Details
{
	#region Private Declarations
	private VCM.EMS.Dal.Details objDetails;
	#endregion

	#region Constructor
	public Details()
	{
		objDetails = new VCM.EMS.Dal.Details();
	}
	#endregion

	#region Public Methods

    public void AddEmployee(System.Int64 empid, string empname, int deptId, string workid, string hiredate)
    {
        objDetails.AddEmployee(empid, empname,deptId, workid, hiredate);
    }
	public int SaveDetails(VCM.EMS.Base.Details objDetailsEntity,System.Int64 oldEmpId)
	{
        return objDetails.SaveDetails(objDetailsEntity, oldEmpId);
	}
    public void Emp_Save_ResignDate(System.Int64 empId, string resignDate)
    {
        objDetails.Emp_Save_ResignDate(empId, resignDate);
    }

	public int DeleteDetails(System.Int64 empId)
	{
		return objDetails.DeleteDetails(empId);
	}
    public string checkIdExistence(System.Int64 value)
    {
        objDetails = new VCM.EMS.Dal.Details();
        return objDetails.checkIdExistence(value);
    }
	public int ActivateInactivateDetails(string strIDs, int modifiedBy, bool isActive)
	{
		return objDetails.ActivateInactivateDetails(strIDs, modifiedBy, isActive);
	}
    public int GetCountEmpByDeptId(System.String deptId)
    {
        return objDetails.GetCountEmpByDeptId(deptId);
    }
    public int GetCountEmpByDocId(System.String documentId)
    {
        return objDetails.GetCountEmpByDocId(documentId);
    }
	public VCM.EMS.Base.Details GetDetailsByID(System.Int64 lempId)
	{
		return objDetails.GetDetailsByID(lempId);
	}
    public DataSet GetByDept(System.Int64 deptId, string fieldName, string order,  string durationflag, string empmonth, string empyear, string empstatus)
    {
        return objDetails.GetByDept(deptId, fieldName, order, durationflag, empmonth, empyear, empstatus);
    }
    public DataSet GetByEmpId(System.Int64 deptId, System.Int32 empId)
    {
        return objDetails.GetByEmpId(deptId, empId);
    }
    public DataSet GetByDept2(System.Int64 deptId, string fieldName, string order, string durationflag, string empmonth, string empyear, string empstatus)
    {
        return objDetails.GetByDept2(deptId, fieldName, order, durationflag, empmonth, empyear, empstatus);
    }
	public DataSet GetAll()
	{
		return objDetails.GetAll();
	}
    public DataSet GetAll2()
    {
        return objDetails.GetAll2();
    }
    public DataSet GetBySearch(string value)
    {
        return objDetails.GetBySearch(value);
    }
    public DataSet GetAllEmpDetailsByDept(System.Int64 empId, System.Int64 deptId, string fieldName, string order, string durationflag, string empmonth, string empyear, string empstatus)
    {
        return objDetails.GetAllEmpDetailsByDept(empId, deptId, fieldName, order, durationflag, empmonth, empyear, empstatus);
    }
    public DataSet GetAllEmpDetails(string fieldName, string order, string durationflag, string empmonth, string empyear, string empstatus)
    {
        return objDetails.GetAllEmpDetails(fieldName, order, durationflag, empmonth,empyear, empstatus);
    }
    public int GetAllEmpByDesign(System.String design)
    {
        return objDetails.GetAllEmpByDesign(design);
    }
    public string getAutoGeneratedEmpId()
    {
        return objDetails.getAutoGeneratedEmpId();
    }

    //method from payslip

    public DataSet GetPayslipEarningsById(System.Int64 empId, int year, int month)
    {
        return objDetails.GetPayslipEarningsById(empId, year, month);
    }
    public DataSet GetPayslipDeductionsById(System.Int64 empId, int year, int month)
    {
        return objDetails.GetPayslipDeductionsById(empId, year, month);
    }
    public decimal PayslipGetCurrentGross(System.Int64 empId, int year, int month)
    {
        return objDetails.PayslipGetCurrentGross(empId, year, month);
    }
    public int PayslipGetTotalDeductions(System.Int64 empId, int year, int month)
    {
        return objDetails.PayslipGetTotalDeductions(empId, year, month);
    }
    public double PayslipGetTDS(System.Int64 empId, int year, int month)
    {
        return objDetails.PayslipGetTDS(empId, year, month);
    }

    public DataSet GetAttendanceLogDetail(int empId, DateTime CurrentDate)
    {
        return objDetails.GetAttendanceLogDetail(empId, CurrentDate);
    }

    public DataSet GetDailyLogDetail(DateTime CurrentDate, int empId)
    {
        return objDetails.GetDailyLogDetail(CurrentDate, empId);
    }

    public DataSet GetTLDetails(int deptId)
    {
        return objDetails.GetTLDetails(deptId);
    }

    public DataSet GetAllActiveEmpDetails(int DeptId,int EmpId)
    {
        return objDetails.GetAllActiveEmpDetails(DeptId,EmpId);
    }
    public DataSet GetEmployeeDetails(System.Int32 empId)
    {
        return objDetails.GetEmployeeDetails(empId);
    }
	#endregion
}
}