using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Data;
using VCM.EMS.Base;
using VCM.EMS.Biz;
using System.Security.Principal;

public partial class HR_AddEmployee : System.Web.UI.Page
{
    public VCM.EMS.Base.Details prop;
    public VCM.EMS.Biz.Details adapt;
    public VCM.EMS.Biz.Departments dpts;
    long empid;
    protected void Page_Load(object sender, EventArgs e)
    {
        prop = new VCM.EMS.Base.Details();
        adapt = new VCM.EMS.Biz.Details();
        dpts = new VCM.EMS.Biz.Departments();
        if (!IsPostBack)
        {
            this.ViewState["SortExp"] = "deptName";
            this.ViewState["SortOrder"] = "ASC";
            filllist();           
        }
    }
    protected void btnSave_Click(object sender, EventArgs e)
    {       
        if (adapt.getAutoGeneratedEmpId() != System.DBNull.Value.ToString())
        {
            empid = Convert.ToInt64(adapt.getAutoGeneratedEmpId()) + 1;
        }
        adapt.AddEmployee(empid, txtEmpName.Text, Convert.ToInt32(deptList.SelectedValue), txtWorkEmail.Text, hireDate.Text);       
        resetcontrols();
    }
    protected void btnCancel_Click(object sender, EventArgs e)
    {
        resetcontrols();
        Response.Redirect("EmployeeList.aspx");
    }
    public void resetcontrols()
    {
        txtEmpName.Text = "";
        deptList.SelectedIndex = -1;
        txtWorkEmail.Text = "";
        hireDate.Text = "";
    }
    public void filllist()
    {
        DataSet ds = new DataSet();
        ds = dpts.GetAll(true, this.ViewState["SortExp"].ToString(), this.ViewState["SortOrder"].ToString());
        deptList.DataSource = ds;
        deptList.DataTextField = "deptName";
        deptList.DataValueField = "deptId";
        deptList.DataBind();
        deptList.Items.Insert(0, "Select..");
        deptList.SelectedIndex = 0;
    }
}
